server:
   port: 9000
spring:
   application:
      name: order-service
   kafka:
      bootstrap-servers: localhost:9092
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
    